import Head from "next/head";
import { Inter } from "next/font/google";
import Form from "@/components/form";
import RegistrationForm from "@/components/registrationForm";
import Admin from "@/components/admin";
import Main from "@/components/main";
import { useEffect, useState } from "react";
import { About } from "@/container/about";
import { scroller, Element } from "react-scroll";
import { Ways } from "@/container/ways";
import { Photo } from "@/container/photo";
import { Questions } from "@/container/questions";
import { Reviews } from "@/container/reviews";
import { Footer } from "@/container/footer";
import { Contact } from "@/container/contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const [isVisible, setIsVisible] = useState(false);

  // let isScrollEnabled = true;
  // let currentIndex = 1;
  // useEffect(() => {
  //   const handleScroll = (e: WheelEvent) => {
  //     console.log(isScrollEnabled);
  //     if (!isScrollEnabled) return;
  //     /* console.log(e.deltaY); */
  //     if (e.deltaY > 0) {
  //       scroller.scrollTo("component2", {
  //         duration: 800,
  //         smooth: true,
  //       });

  //       // scrollToNextComponent();
  //     } else {
  //       scroller.scrollTo("component1", {
  //         duration: 800,
  //         smooth: true,
  //       });
  //     }
  //   };

  //   window.addEventListener("wheel", handleScroll);

  //   return () => {
  //     window.removeEventListener("wheel", handleScroll);
  //   };
  // }, []);
  // const scrollToNextComponent = () => {
  //   isScrollEnabled = false;
  //   setTimeout(() => {
  //     isScrollEnabled = true;
  //   }, 1000);
  //   if (currentIndex === 2) return;
  //   currentIndex++;
  //   const nextComponentName = `component${currentIndex}`;
  //   console.log(nextComponentName);
  //   scroller.scrollTo(nextComponentName, {
  //     duration: 800,
  //     smooth: true,
  //   });
  // };

  return (
    <>
      <Head>
        <title>test next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Element name="component1">
          <Main />
        </Element>
        <Element name="component2">
          <About />
        </Element>
        <Element name="component3">
          <Ways />
        </Element>
        <Photo />
        <Questions />
        <Reviews />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
