import Head from "next/head";
import { Inter } from "next/font/google";
import Form from "@/components/form";
import RegistrationForm from "@/components/registrationForm";
import Admin from "@/components/admin";
import Main from "@/components/main";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const handleScroll = (e: WheelEvent) => {
      console.log(e.deltaY);
      if (e.deltaY > 0) {
        setIsVisible(true);
      } else {
        setIsVisible(false);
      }
    };

    window.addEventListener("wheel", handleScroll);

    return () => {
      window.removeEventListener("wheel", handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>test next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Main />
        {/* <div onWheel={handleWeel}>
          <h1>Первый компонент</h1>

          {isVisible && (
            <div className="second-component">
              <h1>Второй компонент</h1>
              <p>Этот компонент появится при прокрутке вниз</p>
            </div>
          )}
        </div>
        <Form />
        <RegistrationForm />
        <Admin /> */}
      </main>
    </>
  );
}
