import Head from "next/head";
import { Inter } from "next/font/google";
import Form from "@/components/form";
import RegistrationForm from "@/components/registrationForm";
import Admin from "@/components/admin";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>test next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Form />
        <RegistrationForm />
        <Admin />
      </main>
    </>
  );
}
